### ISSUE TITLE
iOS Safari: Charge icon changes shape

### ISSUE THREAD

**Issue by Sigafoos** [pvpoke/pvpoke#33] opened 2019-08-01 01:54 UTC
As I power up my charge moves, the icon changes from a circle to a square. This is on iOS Safari only: OS X Firefox and Chrome don't have the issue.

Video: https://www.youtube.com/watch?v=hK6kfMQRMPk

**Comment by Sigafoos** [comment] 2019-08-01 02:01
Once the `active` class is added to `.move-bar` this is no longer an issue (probably because the height is greater than 100%)

**Comment by pvpoke** [comment] 2019-08-01 16:10
I've played around with some things but haven't found a satisfactory solution yet. Here's a similar issue:

https://stackoverflow.com/questions/17202128/rounded-cornes-border-radius-safari-issue/17210864

The problem is the inner element needs to be square-shaped and change height to produce the image of a circular icon filling up, so giving the inner element a border-radius isn't an option.

A possible solution is to turn the move bars into a non-repeating background image that changes background position as the bar fills up. Fingers crossed this would obey the parent element's border radius!

**Comment by pvpoke** [comment] 2019-08-08 14:29
This should be fixed now! I changed the bars to a background image that changes background position instead of an interior element that changes height.

**Closed by pvpoke** 2019-08-08 14:29 UTC
